
tasks:
  - init: echo 'init script' # runs during prebuild
    command: kotlinc main.kt 

image:
  file: .gitpod.Dockerfile

#vscode:
#  extensions:
#    - mathiasfrohlich.Kotlin@1.7.0:9xQZtwTUg4bdXHCMyxM7vQ==
#    - fwcd.kotlin@0.2.11:moh8IDanzsIlhtK2IeiLmQ==
vscode:
  extensions:
    - mathiasfrohlich.Kotlin
    - fwcd.kotlin