import com.withgoogle.codingcompetitions.task.*

// $ gradle newhello -Pclazz="something"
val clazz: String by project

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.withgoogle.codingcompetitions.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.

    var mainClazz = ""
    if( project.hasProperty("clazz")){
        mainClazz = "com.withgoogle.codingcompetitions.app."+clazz
        println(mainClazz)
    }
    mainClass.set(mainClazz)
//    mainClass.set("com.withgoogle.codingcompetitions.app.AppKt")
}

tasks.register("newtask") {
    doLast {
        println("newtask -> doLast")
    }
    doFirst{
        println("newtask -> doFirst")
    }
    println("newtask -> !!!!!!!!!! ")
}

tasks.register<GreetingTask>("newhello") {
    doLast {
        println("newhello -> doLast")
    }
    doFirst{
        println("newhello -> doFirst")
    }
    if( project.hasProperty("clazz")){
        println(clazz)
    }
    println("newhello -> !!!!!!!!!! ")
}